[build]
  base = "/"               # 基础目录（通常是项目根目录）
  publish = "frontend/dist"   # 前端构建后的输出目录
  command = "sed -i \"s|API_URL_PLACEHOLDER|${API_URL}|g\" netlify.toml && cd frontend && npm install && npm run build"  # 构建命令
  ignore = "git diff --quiet HEAD^ HEAD ./frontend/"  # 只在前端目录有变更时才构建

# 缓存设置以加速构建
[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-audit --prefer-offline"

# 重定向规则
[[redirects]]
  from = "/api/*"
  to = "API_URL_PLACEHOLDER/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# 添加自定义头部提高安全性
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"