[build]
  base = "/"               # 基础目录（通常是项目根目录）
  publish = "frontend/dist"   # 前端构建后的输出目录
  command = "cd frontend && npm install && npm run build"  # 构建命令

# 重定向规则
[[redirects]]
  from = "/api/*"
  to = "http://47.115.227.145:5010/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}